### ISSUE TITLE
not an issue - question on deploying to mobile

### ISSUE THREAD

**Issue by johndpope** [Vivino/rankdb#12]
I'm wanting to achieve a rankdb with 100,000 entries on mobile
I'd rather not poll for updates. Did you consider an architecture besides http for updates?
mqtt / firebase / pubnub etc ? 

P.s - is there a simple way to get the test data into docker
https://github.com/Vivino/rankdb/releases/tag/sample

**Comment by klauspost** [comment]
A pubsub or similar cannot be made reasonably scalable since a single update could generate thousands of notifications.

A polling solution will remain scalable and easier to control.

That being said it should be pretty easy to write a piece of software that pulls the current list at fixed intervals and diffs for updates.

**Comment by johndpope** [comment]
Thanks Klaus - I'm building a competition platform - 8secondz.app - and really want to embrace this tech stack. Perhaps you should surface a patreon sponsorship link - if we get live and eyeballs - I could see us wanting to continue to kick back to this project.

Did this get battle tested on a public website / property? or just intranet / internal?
or is this kind of an academic excercise? 

P.P.s - is there a simple way to get the test data into docker
https://github.com/Vivino/rankdb/releases/tag/sample

**Comment by eikmadsen** [comment]
Its been running fine in production for several years now. 
Peaking at around 3000 requests per second, roughly 96%+ reads.

**Comment by eikmadsen** [comment]
The `rankdb-cli --timeout=5m restore multilist --src="file" --src_file="github-ranks-backup.bin.zst"` doesn't work for you ? @johndpope

**Comment by johndpope** [comment]
thx
