### ISSUE TITLE
Add dockerhub repo

### ISSUE THREAD

**Issue by klauspost** [Vivino/rankdb#2]
Add to dockerhub.

It should be possible to set up so tags are automatically updated.

**Comment by zvymazal** [comment]
Docker repository `vivino/rankdb` has been created and connected with GitHub. New releases should automatically be build and published.

**Comment by klauspost** [comment]
@zvymazal Should we release a new version to test it?

**Comment by zvymazal** [comment]
Yes 👍

**Comment by klauspost** [comment]
Will do. I have a dependency update as well.

**Comment by klauspost** [comment]
We might as well include #4 as well, but maybe with Go 1.13?

**Comment by klauspost** [comment]
I had to add another `GITHUB_TOKEN` to travis, since releases are seen as branches and it was only available to master.

Anyway releases are working, but not so sure about dockerhub. Shouldn't there be something here: https://hub.docker.com/r/vivino/rankdb

**Comment by zvymazal** [comment]
There was some configuration missing. I'm testing it now.

**Comment by zvymazal** [comment]
The Docker image builds are breaking on these two:

COPY api/conf/conf.stub.toml /conf/conf.toml -> COPY conf/conf.stub.toml /conf/conf.toml
COPY deploy/docker-entrypoint.sh /usr/bin/ -> ?

**Comment by klauspost** [comment]
Still have the file. Lemme update.

**Comment by zvymazal** [comment]
🎉 https://hub.docker.com/r/vivino/rankdb/tags

**Comment by zvymazal** [comment]
The rules are configured to build master and release tags.
